image:
  file: .gitpod.dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      composer install
      gp sync-done installation

  - init: |
      mysql 
      gp sync-done installation

  - init: gp sync-await installation
    command: php -S localhost:8080 -t public

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-preview
